######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 13 22:05:03 2008
######################################################################

TEMPLATE = app
CONFIG += qt warn_off debug
TARGET = amarokquilt
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
