######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 15 19:26:02 2008
######################################################################

TEMPLATE = app
CONFIG += qt warn_off debug
TARGET = amarokquilt
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += nowplayingitem.h amarokquilt.h
SOURCES += main.cpp amarokquilt.cpp nowplayingitem.cpp
